// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configurações de fallback caso as variáveis de ambiente não estejam disponíveis
const fallbackSupabaseUrl = "https://wvojbjkdlnvlqgjwtdaf.supabase.co";
const fallbackSupabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2b2piamtkbG52bHFnanF3dGRhZiIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzM1NzI5NzE5LCJleHAiOjIwNTEzMDU3MTl9.juWlSIl6oLFH43Ii39TQ1p55scz04uhDj0TVjNduH0k";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || fallbackSupabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || fallbackSupabaseKey;

// Debug: Verificar se as variáveis de ambiente estão sendo carregadas
console.log('Supabase Config:', {
  url: SUPABASE_URL ? '✅ Configurado' : '❌ Não configurado',
  key: SUPABASE_PUBLISHABLE_KEY ? '✅ Configurado' : '❌ Não configurado'
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false, // Desabilita persistência de sessão
    autoRefreshToken: false, // Desabilita refresh automático de token
    detectSessionInUrl: false, // Desabilita detecção de sessão na URL
  }
});

// Função para atualizar o header Authorization dinamicamente
export async function setSupabaseAuthToken(token: string) {
  // Não precisamos mais definir sessão do Supabase, pois usamos apenas Firebase
  // Esta função é mantida para compatibilidade, mas não faz nada
  console.log('Supabase auth token set (Firebase auth used instead)');
}