// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvojbjkdlnvlqgjwtdaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2b2piamtkbG52bHFnand0ZGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjEwMzcsImV4cCI6MjA2OTAzNzAzN30.juWlSIl6oLFH43Ii39TQ1p55scz04uhDj0TVjNduH0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false, // Desabilita persistência de sessão
    autoRefreshToken: false, // Desabilita refresh automático de token
    detectSessionInUrl: false, // Desabilita detecção de sessão na URL
  }
});

// Função para atualizar o header Authorization dinamicamente
export async function setSupabaseAuthToken(token: string) {
  // Não precisamos mais definir sessão do Supabase, pois usamos apenas Firebase
  // Esta função é mantida para compatibilidade, mas não faz nada
  console.log('Supabase auth token set (Firebase auth used instead)');
}